name: flake.lock updater

on:
  schedule:
    - cron: "30 8 * * 6/2"
  workflow_dispatch:

jobs:
  flake-updater:
    name: flake.lock updater
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-title: "chore: update flake.lock"
