name: Flake check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  flake-check:
    name: Check flake.lock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
